### ISSUE TITLE
Problem with max_pods

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-eks-installer#16]
Hi team, when using EKS clusters, makes no sense to set max_pods because the size of the ec2 instance implies the maximum number of ENI that can be attached to a node, see:
https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

We should use this list, maybe create a map and use the value from the map to set the max pods for the nodes

**Comment by angelbarrera92** [comment]
Does it also affect if you changed the default cni to canico?

**Comment by nutellinoit** [comment]
AFAIK we don't change CNI to calico on EKS

**Comment by lnovara** [comment]
No, we stick to VPC CNI. On EKS there is no need to expose such variable.

**Comment by angelbarrera92** [comment]
Ye, the idea to expose that variable is to enable changing the CNI from VPC CNI to any other (calico mostly).
Then, what we can do is to make that variable somehow optional. What do you think?

**Comment by nutellinoit** [comment]
> Ye, the idea to expose that variable is to enable changing the CNI from VPC CNI to any other (calico mostly).
> Then, what we can do is to make that variable somehow optional. What do you think?

This is a problem using EKS. We should use the official values https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt or, omit the max_pods completely if possible.

We use calico on EKS only to add networkpolicy capability.

**Comment by angelbarrera92** [comment]
Addressed on v1.8.1 in:

- AKS
- EKS
- GKE

SIGHUP cloud installers :)
