### ISSUE TITLE
Test EKS Installer against 1.24 version

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-eks-installer#37]
[AWS has released support for Kubernetes 1.24 in EKS](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/). Test if the installer is capable of creating a 1.24 cluster.

Create issues with the eventual changes that need to be made.

**Comment by nutellinoit** [comment]
The installer works as it is, no need to update
