### ISSUE TITLE
Check if the installer uses Auto Scaling launch configurations

### ISSUE THREAD

**Issue by nohant** [sighupio/fury-eks-installer#39]
check if in the Terraform module we use under the hood launch templates.
because launch configuration are going to be dismissed december 1

**Comment by ralgozino** [comment]
december 1 or december 31?

**Comment by nohant** [comment]
december 31, sorry, i missed the 3 in the description 🦆 
it will be a progressive dismission:

- December 31, 2022
No new EC2 features or new EC2 instance types will be added to launch configurations after this date.

- March 31, 2023
New accounts created after this date will not be able to create new launch configurations via the console. API and CLI access will remain available to support customers with automation use cases.

- December 31, 2023
New accounts created after this date will not be able to create new launch configurations.
