### ISSUE TITLE
Test EKS Installer against 1.25 version

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-eks-installer#47]

**Comment by ralgozino** [comment]
At the time of this writing, EKS itself does not support Kubernetes 1.25 yet. According to their release calendar, it will be added in March 2023.

References:

- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions
- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by nutellinoit** [comment]
Nice! Let's close this as completed
