### ISSUE TITLE
Write the v1.11 to v2.0 upgrade guide

### ISSUE THREAD

**Issue by omissis** [sighupio/fury-eks-installer#57]
Please write the full upgrade guide for the installer.
It was initially described [here](https://github.com/sighupio/fury-eks-installer/pull/52/files#diff-14b3623f87fbe14c3f4c1702e234527a7eccc20b90b3b2c974a44f8cb9c2ca50), but [later works](https://github.com/sighupio/fury-eks-installer/pull/53/files/b526f84e47f039cc45c2fd72e992e931224e8fcb#commit-suggestions) caused that guide to go out of sync, so we should update the whole thing once it's well tested.

Keep in mind that the guide above was including a lot of furyctl details: we should limit the procedure to the installer, and move the furyctl-specific instructions in the furyctl documentation.

**Comment by nutellinoit** [comment]
closing as completed, manual guide can be found here: https://github.com/sighupio/fury-eks-installer/blob/main/docs/upgrades/v1.11.x-to-v2.0.x.md
